/**
 * Golden tests — oscillator extensions (CMO, TRIX, PPO, PVO, BOP, AO, AC, DPO,
 * KST, Coppock, Fisher Transform, Connors RSI, Chande Forecast Oscillator).
 *
 * Reference vectors (see oscillators_ext.vectors.ts, GENERATED by the scratch
 * TA-Lib 0.6.8 oracle over the seed-42 220-bar close fixture and a seed-7 OHLC
 * jitter around it):
 *  - CMO / TRIX / BOP                  = TA-Lib 0.6.8 direct (asserted at 1e-6).
 *  - PPO / PVO                         = the published StockCharts/TradingView PPO
 *                                        definition 100*(EMA_f-EMA_s)/EMA_s computed
 *                                        from the TA-Lib EMA primitive (PVO is the
 *                                        same on volume). NOTE: TA-Lib's own PPO/APO
 *                                        use a non-standard alignment that does NOT
 *                                        equal EMA_f-EMA_s, so we follow the published
 *                                        formula (matching how macd() composes its
 *                                        line); asserted at 1e-6.
 *  - CFO                               = published CFO formula with the LinReg
 *                                        endpoint = TA-Lib 0.6.8 LINEARREG (1e-6).
 *  - AO / AC                           = Bill Williams published formula computed
 *                                        over the OHLC fixture (1e-6).
 *  - DPO                               = StockCharts published DPO formula (1e-6).
 *  - KST + signal                      = Pring published KST formula (1e-6).
 *  - Coppock                           = Coppock published WMA-of-ROC-sum (1e-6).
 *  - Fisher + trigger                  = Ehlers published Fisher Transform (1e-6).
 *  - Connors RSI                       = Connors published formula; the two RSI
 *                                        components are the Wilder/TA-Lib RSI
 *                                        already golden-tested in momentum (1e-6).
 *
 * Every indicator below pins: golden vector at the stated epsilon, the NaN
 * warmup-prefix length, a div-by-zero / flat-range gotcha, determinism, and the
 * registry def reproducing the bare-function series via OHLCV. EXCLUDED: none —
 * all 13 had an authoritative reference vector.
 */

import { describe, expect, it } from "vitest";
import {
  acceleratorOscillator,
  awesomeOscillator,
  bop,
  chandeForecastOscillator,
  cmo,
  connorsRsi,
  coppock,
  createCMO,
  dpo,
  fisherTransform,
  kst,
  oscillatorsExtIndicators,
  ppo,
  trix,
} from "./oscillators_ext";
import {
  AC,
  AO,
  BOP,
  CFO14,
  CLOSE,
  CMO14,
  COPPOCK,
  CRSI,
  DPO20,
  FISHER,
  FISHER_TRIGGER,
  HIGH,
  KST,
  KST_SIGNAL,
  LOW,
  OPEN,
  PPO_12_26,
  PVO_12_26,
  TRIX14,
  VOL_OHLC,
} from "./oscillators_ext.vectors";
import type { OHLCV } from "./types";
import { assertCloseArray, expectDeterministic, nanPrefixLength, runStream } from "./test-helpers";

const EPS = 1e-6;

/** Build OHLCV bars from the OHLC fixture arrays (+ volume). */
const ohlcBars = (): OHLCV[] =>
  CLOSE.map((c, i) => ({
    time: i * 60000,
    open: OPEN[i]!,
    high: HIGH[i]!,
    low: LOW[i]!,
    close: c,
    volume: VOL_OHLC[i]!,
  }));

/** Build bars from a flat close array (high=low=open=close), optional volume. */
const closeBars = (xs: number[], vols?: number[]): OHLCV[] =>
  xs.map((c, i) => ({
    time: i * 60000,
    open: c,
    high: c,
    low: c,
    close: c,
    volume: vols ? vols[i]! : 0,
  }));

describe("CMO — golden vs TA-Lib 0.6.8", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(cmo(CLOSE, 14), CMO14, EPS, "CMO14");
  });
  it("NaN warmup prefix is exactly period (first value at index period)", () => {
    expect(nanPrefixLength(cmo(CLOSE, 14))).toBe(14);
  });
  it("gotcha: a monotonically rising series with no losses -> +100", () => {
    const out = cmo([1, 2, 3, 4, 5, 6], 3);
    expect(out[3]).toBeCloseTo(100, 9);
  });
  it("gotcha: a flat series (no moves) -> 0 (no div-by-zero)", () => {
    const out = cmo([5, 5, 5, 5, 5, 5], 3);
    expect(out.slice(3).every((v) => v === 0)).toBe(true);
  });
  it("streaming CMO reproduces the batch series exactly", () => {
    assertCloseArray(runStream(createCMO(14), CLOSE), CMO14, EPS, "stream CMO14");
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => cmo(CLOSE, 14));
  });
});

describe("TRIX — golden vs TA-Lib 0.6.8", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(trix(CLOSE, 14), TRIX14, EPS, "TRIX14");
  });
  it("NaN warmup prefix is exactly 3*(period-1)+1", () => {
    expect(nanPrefixLength(trix(CLOSE, 14))).toBe(40);
  });
  it("gotcha: too-short series is all-NaN", () => {
    expect(trix(CLOSE.slice(0, 39), 14).every(Number.isNaN)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => trix(CLOSE, 14));
  });
});

describe("PPO — golden vs standard PPO (TA-Lib EMA, StockCharts/TradingView)", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(ppo(CLOSE, 12, 26), PPO_12_26, EPS, "PPO");
  });
  it("NaN warmup prefix is exactly slow-1", () => {
    expect(nanPrefixLength(ppo(CLOSE, 12, 26))).toBe(25);
  });
  it("gotcha: a flat series -> 0 (numerator 0, denom nonzero)", () => {
    const flat = new Array(40).fill(50);
    const out = ppo(flat, 12, 26);
    expect(out.slice(25).every((v) => Math.abs(v) < 1e-12)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => ppo(CLOSE, 12, 26));
  });
});

describe("PVO — golden vs standard percentage oscillator on volume (TA-Lib EMA)", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(ppo(VOL_OHLC, 12, 26), PVO_12_26, EPS, "PVO");
  });
  it("NaN warmup prefix is exactly slow-1", () => {
    expect(nanPrefixLength(ppo(VOL_OHLC, 12, 26))).toBe(25);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => ppo(VOL_OHLC, 12, 26));
  });
});

describe("BOP — golden vs TA-Lib 0.6.8", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(bop(ohlcBars()), BOP, EPS, "BOP");
  });
  it("no warmup: first value at index 0", () => {
    expect(nanPrefixLength(bop(ohlcBars()))).toBe(0);
  });
  it("gotcha: a flat bar (high == low) -> 0 (no div-by-zero)", () => {
    const bars: OHLCV[] = [{ time: 0, open: 5, high: 5, low: 5, close: 5, volume: 0 }];
    expect(bop(bars)[0]).toBe(0);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => bop(ohlcBars()));
  });
});

describe("AO — golden vs Bill Williams published formula", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(awesomeOscillator(ohlcBars(), 5, 34), AO, EPS, "AO");
  });
  it("NaN warmup prefix is exactly slow-1", () => {
    expect(nanPrefixLength(awesomeOscillator(ohlcBars(), 5, 34))).toBe(33);
  });
  it("gotcha: too-short series is all-NaN", () => {
    expect(awesomeOscillator(ohlcBars().slice(0, 33), 5, 34).every(Number.isNaN)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => awesomeOscillator(ohlcBars(), 5, 34));
  });
});

describe("AC — golden vs Bill Williams published formula", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(acceleratorOscillator(ohlcBars(), 5, 34, 5), AC, EPS, "AC");
  });
  it("NaN warmup prefix is (slow-1) + (smaPeriod-1) = 37", () => {
    expect(nanPrefixLength(acceleratorOscillator(ohlcBars(), 5, 34, 5))).toBe(37);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => acceleratorOscillator(ohlcBars(), 5, 34, 5));
  });
});

describe("DPO — golden vs StockCharts published formula", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(dpo(CLOSE, 20), DPO20, EPS, "DPO20");
  });
  it("NaN warmup prefix is exactly period-1", () => {
    expect(nanPrefixLength(dpo(CLOSE, 20))).toBe(19);
  });
  it("gotcha: a flat series -> 0 (price equals its own SMA)", () => {
    const flat = new Array(30).fill(7);
    const out = dpo(flat, 20);
    expect(out.slice(19).every((v) => Math.abs(v) < 1e-12)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => dpo(CLOSE, 20));
  });
});

describe("KST — golden vs Pring published formula", () => {
  it("KST line matches the reference within 1e-6", () => {
    assertCloseArray(kst(CLOSE).kst, KST, EPS, "KST");
  });
  it("signal line matches the reference within 1e-6", () => {
    assertCloseArray(kst(CLOSE).signal, KST_SIGNAL, EPS, "KST signal");
  });
  it("KST warmup prefix is 44; signal warmup is 52", () => {
    expect(nanPrefixLength(kst(CLOSE).kst)).toBe(44);
    expect(nanPrefixLength(kst(CLOSE).signal)).toBe(52);
  });
  it("gotcha: too-short series is all-NaN", () => {
    expect(kst(CLOSE.slice(0, 44)).kst.every(Number.isNaN)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => kst(CLOSE).kst);
  });
});

describe("Coppock — golden vs published formula", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(coppock(CLOSE, 14, 11, 10), COPPOCK, EPS, "Coppock");
  });
  it("NaN warmup prefix is longRoc + (wmaPeriod-1) = 23", () => {
    expect(nanPrefixLength(coppock(CLOSE, 14, 11, 10))).toBe(23);
  });
  it("gotcha: too-short series is all-NaN", () => {
    expect(coppock(CLOSE.slice(0, 23), 14, 11, 10).every(Number.isNaN)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => coppock(CLOSE, 14, 11, 10));
  });
});

describe("Fisher Transform — golden vs Ehlers published formula", () => {
  it("fisher line matches the reference within 1e-6", () => {
    assertCloseArray(fisherTransform(ohlcBars(), 9).fisher, FISHER, EPS, "Fisher");
  });
  it("trigger (1-bar lag of fisher) matches the reference within 1e-6", () => {
    assertCloseArray(fisherTransform(ohlcBars(), 9).trigger, FISHER_TRIGGER, EPS, "Fisher trig");
  });
  it("NaN warmup prefix is exactly period-1", () => {
    expect(nanPrefixLength(fisherTransform(ohlcBars(), 9).fisher)).toBe(8);
  });
  it("gotcha: a flat-range window -> raw 0, finite (no div-by-zero / log blowup)", () => {
    const bars = closeBars(new Array(20).fill(10));
    const out = fisherTransform(bars, 9).fisher;
    expect(out.slice(8).every(Number.isFinite)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => fisherTransform(ohlcBars(), 9).fisher);
  });
});

describe("Connors RSI — golden vs published formula", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(connorsRsi(CLOSE, 3, 2, 100), CRSI, EPS, "CRSI");
  });
  it("NaN warmup prefix is exactly rankPeriod (100)", () => {
    expect(nanPrefixLength(connorsRsi(CLOSE, 3, 2, 100))).toBe(100);
  });
  it("gotcha: too-short series (< rankPeriod) is all-NaN", () => {
    expect(connorsRsi(CLOSE.slice(0, 100), 3, 2, 100).every(Number.isNaN)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => connorsRsi(CLOSE, 3, 2, 100));
  });
});

describe("CFO — golden vs published formula (LinReg = TA-Lib LINEARREG)", () => {
  it("matches the reference within 1e-6", () => {
    assertCloseArray(chandeForecastOscillator(CLOSE, 14), CFO14, EPS, "CFO14");
  });
  it("NaN warmup prefix is exactly period-1", () => {
    expect(nanPrefixLength(chandeForecastOscillator(CLOSE, 14))).toBe(13);
  });
  it("gotcha: a perfectly linear series -> 0 (close equals its regression fit)", () => {
    const lin = Array.from({ length: 30 }, (_, i) => 10 + 0.5 * i);
    const out = chandeForecastOscillator(lin, 14);
    expect(out.slice(13).every((v) => Math.abs(v) < 1e-9)).toBe(true);
  });
  it("deterministic: same input -> identical output", () => {
    expectDeterministic(() => chandeForecastOscillator(CLOSE, 14));
  });
});

describe("oscillators_ext registry defs compute via OHLCV", () => {
  it("each def reproduces the bare-function series", () => {
    const bars = ohlcBars();
    const find = (id: string) => oscillatorsExtIndicators.find((d) => d.id === id)!;
    assertCloseArray(find("cmo").compute(bars, { period: 14 }) as number[], CMO14, EPS, "def CMO");
    assertCloseArray(
      find("trix").compute(bars, { period: 14 }) as number[],
      TRIX14,
      EPS,
      "def TRIX"
    );
    assertCloseArray(
      find("ppo").compute(bars, { fast: 12, slow: 26 }) as number[],
      PPO_12_26,
      EPS,
      "def PPO"
    );
    assertCloseArray(
      find("pvo").compute(bars, { fast: 12, slow: 26 }) as number[],
      PVO_12_26,
      EPS,
      "def PVO"
    );
    assertCloseArray(find("bop").compute(bars, {}) as number[], BOP, EPS, "def BOP");
    assertCloseArray(
      find("ao").compute(bars, { fast: 5, slow: 34 }) as number[],
      AO,
      EPS,
      "def AO"
    );
    assertCloseArray(
      find("ac").compute(bars, { fast: 5, slow: 34, smaPeriod: 5 }) as number[],
      AC,
      EPS,
      "def AC"
    );
    assertCloseArray(find("dpo").compute(bars, { period: 20 }) as number[], DPO20, EPS, "def DPO");
    const kstDef = find("kst").compute(bars, {}) as Record<string, number[]>;
    assertCloseArray(kstDef.kst!, KST, EPS, "def KST");
    assertCloseArray(kstDef.signal!, KST_SIGNAL, EPS, "def KST signal");
    assertCloseArray(
      find("coppock").compute(bars, { longRoc: 14, shortRoc: 11, wmaPeriod: 10 }) as number[],
      COPPOCK,
      EPS,
      "def Coppock"
    );
    const fishDef = find("fisher").compute(bars, { period: 9 }) as Record<string, number[]>;
    assertCloseArray(fishDef.fisher!, FISHER, EPS, "def Fisher");
    assertCloseArray(fishDef.trigger!, FISHER_TRIGGER, EPS, "def Fisher trig");
    assertCloseArray(
      find("crsi").compute(bars, { rsiPeriod: 3, streakPeriod: 2, rankPeriod: 100 }) as number[],
      CRSI,
      EPS,
      "def CRSI"
    );
    assertCloseArray(find("cfo").compute(bars, { period: 14 }) as number[], CFO14, EPS, "def CFO");
  });
});
