/**
 * Curated, in-repo list of common Indian market symbols for the $cashtag
 * composer typeahead. Deliberately lightweight — the full NSE/BSE symbol master
 * and per-symbol stream pages are a later roadmap item (rank 6); this list only
 * needs to surface the most liquid names while typing. Any $SYMBOL the user
 * types is still accepted (free-entry), so an absent ticker is never blocking.
 *
 * No live data, no network — pure constants so the cashtag suggestions resolve
 * client-side with zero latency. Symbols are uppercase NSE trading symbols
 * (indices first, then ~150 liquid stocks roughly by market cap / turnover).
 */

/** Indices + headline derivatives underlyings. */
const INDICES = ["NIFTY", "BANKNIFTY", "FINNIFTY", "MIDCPNIFTY", "SENSEX", "BANKEX"] as const;

/** ~150 of the most liquid / widely-discussed NSE equities (uppercase symbols). */
const STOCKS = [
  "RELIANCE",
  "TCS",
  "HDFCBANK",
  "ICICIBANK",
  "INFY",
  "SBIN",
  "BHARTIARTL",
  "ITC",
  "LT",
  "KOTAKBANK",
  "AXISBANK",
  "HINDUNILVR",
  "BAJFINANCE",
  "MARUTI",
  "ASIANPAINT",
  "HCLTECH",
  "SUNPHARMA",
  "TITAN",
  "ULTRACEMCO",
  "WIPRO",
  "ONGC",
  "NTPC",
  "POWERGRID",
  "TATAMOTORS",
  "TATASTEEL",
  "JSWSTEEL",
  "ADANIENT",
  "ADANIPORTS",
  "ADANIPOWER",
  "ADANIGREEN",
  "COALINDIA",
  "NESTLEIND",
  "BAJAJFINSV",
  "BAJAJ-AUTO",
  "M&M",
  "TECHM",
  "INDUSINDBK",
  "GRASIM",
  "HINDALCO",
  "DRREDDY",
  "CIPLA",
  "DIVISLAB",
  "BRITANNIA",
  "EICHERMOT",
  "HEROMOTOCO",
  "APOLLOHOSP",
  "TATACONSUM",
  "BPCL",
  "IOC",
  "HINDPETRO",
  "GAIL",
  "VEDL",
  "DLF",
  "PIDILITIND",
  "DABUR",
  "GODREJCP",
  "MARICO",
  "COLPAL",
  "HAVELLS",
  "SIEMENS",
  "ABB",
  "BOSCHLTD",
  "BEL",
  "HAL",
  "BHEL",
  "SAIL",
  "NMDC",
  "JINDALSTEL",
  "PNB",
  "BANKBARODA",
  "CANBK",
  "UNIONBANK",
  "IDFCFIRSTB",
  "FEDERALBNK",
  "BANDHANBNK",
  "AUBANK",
  "INDHOTEL",
  "TRENT",
  "DMART",
  "ZOMATO",
  "PAYTM",
  "NYKAA",
  "POLICYBZR",
  "IRCTC",
  "IRFC",
  "RVNL",
  "PFC",
  "RECLTD",
  "LICI",
  "SBILIFE",
  "HDFCLIFE",
  "ICICIPRULI",
  "ICICIGI",
  "BAJAJHLDNG",
  "SHRIRAMFIN",
  "CHOLAFIN",
  "MUTHOOTFIN",
  "LTIM",
  "LTTS",
  "PERSISTENT",
  "COFORGE",
  "MPHASIS",
  "OFSS",
  "TATAELXSI",
  "TATAPOWER",
  "TORNTPOWER",
  "JSWENERGY",
  "AMBUJACEM",
  "ACC",
  "SHREECEM",
  "DALBHARAT",
  "RAMCOCEM",
  "PIIND",
  "UPL",
  "SRF",
  "DEEPAKNTR",
  "AARTIIND",
  "TATACHEM",
  "LUPIN",
  "AUROPHARMA",
  "BIOCON",
  "ALKEM",
  "TORNTPHARM",
  "ZYDUSLIFE",
  "GLENMARK",
  "MANKIND",
  "MAXHEALTH",
  "FORTIS",
  "DIXON",
  "POLYCAB",
  "KEI",
  "CGPOWER",
  "ABCAPITAL",
  "ABFRL",
  "PAGEIND",
  "BERGEPAINT",
  "VOLTAS",
  "BLUESTARCO",
  "ASHOKLEY",
  "TVSMOTOR",
  "MOTHERSON",
  "BALKRISIND",
  "MRF",
  "APOLLOTYRE",
  "ESCORTS",
  "TIINDIA",
  "CUMMINSIND",
  "INDIGO",
  "GMRINFRA",
  "IDEA",
  "YESBANK",
  "INDUSTOWER",
  "PETRONET",
  "OIL",
  "MGL",
  "IGL",
  "GUJGASLTD",
  "NHPC",
  "SJVN",
  "CONCOR",
  "BHARATFORG",
  "ABBOTINDIA",
  "JUBLFOOD",
  "NAUKRI",
  "INDIANB",
  "MFSL",
] as const;

/** All known symbols, indices first. De-duplicated (a couple of names repeat). */
export const COMMON_SYMBOLS: readonly string[] = [...new Set<string>([...INDICES, ...STOCKS])];

/** Fast membership set for "is this a curated symbol?" checks. */
const SYMBOL_SET = new Set(COMMON_SYMBOLS);

export function isKnownSymbol(symbol: string): boolean {
  return SYMBOL_SET.has(symbol.toUpperCase());
}
