/**
 * In-repo NSE/BSE symbol master for the $cashtag feature: composer typeahead,
 * cashtag linkification, and the per-symbol stream pages (/community/s/[symbol]).
 *
 * Deliberately a committed STATIC list -- no market-data API, no network, no
 * live prices. It covers the headline indices plus the most liquid / widely-
 * discussed NSE equities (roughly by turnover / F&O participation). Any $SYMBOL
 * a user types is still accepted as a free-entry ticker, so an absent name is
 * never blocking -- the master only enriches known symbols with a company name
 * and exchange for nicer chips and stream-page headers.
 *
 * Each record is { symbol, name, exchange }. Symbols are uppercase NSE/BSE
 * trading symbols. Lookups normalize to uppercase.
 */

export type Exchange = "NSE" | "BSE";

export interface SymbolInfo {
  /** Uppercase trading symbol, e.g. "RELIANCE", "NIFTY", "BAJAJ-AUTO". */
  symbol: string;
  /** Human company / index name for headers and chips. */
  name: string;
  exchange: Exchange;
}

/** Indices + headline derivatives underlyings (NSE then BSE). */
const INDICES: readonly SymbolInfo[] = [
  { symbol: "NIFTY", name: "Nifty 50", exchange: "NSE" },
  { symbol: "BANKNIFTY", name: "Nifty Bank", exchange: "NSE" },
  { symbol: "FINNIFTY", name: "Nifty Financial Services", exchange: "NSE" },
  { symbol: "MIDCPNIFTY", name: "Nifty Midcap Select", exchange: "NSE" },
  { symbol: "NIFTYNXT50", name: "Nifty Next 50", exchange: "NSE" },
  { symbol: "SENSEX", name: "BSE Sensex", exchange: "BSE" },
  { symbol: "BANKEX", name: "BSE Bankex", exchange: "BSE" },
  { symbol: "SENSEX50", name: "BSE Sensex 50", exchange: "BSE" },
];

/** The most liquid / widely-discussed NSE equities (uppercase symbols). */
const STOCKS: readonly SymbolInfo[] = [
  { symbol: "RELIANCE", name: "Reliance Industries", exchange: "NSE" },
  { symbol: "TCS", name: "Tata Consultancy Services", exchange: "NSE" },
  { symbol: "HDFCBANK", name: "HDFC Bank", exchange: "NSE" },
  { symbol: "ICICIBANK", name: "ICICI Bank", exchange: "NSE" },
  { symbol: "INFY", name: "Infosys", exchange: "NSE" },
  { symbol: "SBIN", name: "State Bank of India", exchange: "NSE" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", exchange: "NSE" },
  { symbol: "ITC", name: "ITC", exchange: "NSE" },
  { symbol: "LT", name: "Larsen & Toubro", exchange: "NSE" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", exchange: "NSE" },
  { symbol: "AXISBANK", name: "Axis Bank", exchange: "NSE" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", exchange: "NSE" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", exchange: "NSE" },
  { symbol: "MARUTI", name: "Maruti Suzuki India", exchange: "NSE" },
  { symbol: "ASIANPAINT", name: "Asian Paints", exchange: "NSE" },
  { symbol: "HCLTECH", name: "HCL Technologies", exchange: "NSE" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries", exchange: "NSE" },
  { symbol: "TITAN", name: "Titan Company", exchange: "NSE" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", exchange: "NSE" },
  { symbol: "WIPRO", name: "Wipro", exchange: "NSE" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", exchange: "NSE" },
  { symbol: "NTPC", name: "NTPC", exchange: "NSE" },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India", exchange: "NSE" },
  { symbol: "TATAMOTORS", name: "Tata Motors", exchange: "NSE" },
  { symbol: "TATASTEEL", name: "Tata Steel", exchange: "NSE" },
  { symbol: "JSWSTEEL", name: "JSW Steel", exchange: "NSE" },
  { symbol: "ADANIENT", name: "Adani Enterprises", exchange: "NSE" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", exchange: "NSE" },
  { symbol: "ADANIPOWER", name: "Adani Power", exchange: "NSE" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", exchange: "NSE" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions", exchange: "NSE" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", exchange: "NSE" },
  { symbol: "ACC", name: "ACC", exchange: "NSE" },
  { symbol: "COALINDIA", name: "Coal India", exchange: "NSE" },
  { symbol: "NESTLEIND", name: "Nestle India", exchange: "NSE" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", exchange: "NSE" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", exchange: "NSE" },
  { symbol: "M&M", name: "Mahindra & Mahindra", exchange: "NSE" },
  { symbol: "TECHM", name: "Tech Mahindra", exchange: "NSE" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", exchange: "NSE" },
  { symbol: "GRASIM", name: "Grasim Industries", exchange: "NSE" },
  { symbol: "HINDALCO", name: "Hindalco Industries", exchange: "NSE" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories", exchange: "NSE" },
  { symbol: "CIPLA", name: "Cipla", exchange: "NSE" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", exchange: "NSE" },
  { symbol: "BRITANNIA", name: "Britannia Industries", exchange: "NSE" },
  { symbol: "EICHERMOT", name: "Eicher Motors", exchange: "NSE" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", exchange: "NSE" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise", exchange: "NSE" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", exchange: "NSE" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation", exchange: "NSE" },
  { symbol: "IOC", name: "Indian Oil Corporation", exchange: "NSE" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation", exchange: "NSE" },
  { symbol: "GAIL", name: "GAIL (India)", exchange: "NSE" },
  { symbol: "VEDL", name: "Vedanta", exchange: "NSE" },
  { symbol: "DLF", name: "DLF", exchange: "NSE" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", exchange: "NSE" },
  { symbol: "DABUR", name: "Dabur India", exchange: "NSE" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", exchange: "NSE" },
  { symbol: "MARICO", name: "Marico", exchange: "NSE" },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India)", exchange: "NSE" },
  { symbol: "HAVELLS", name: "Havells India", exchange: "NSE" },
  { symbol: "SIEMENS", name: "Siemens", exchange: "NSE" },
  { symbol: "ABB", name: "ABB India", exchange: "NSE" },
  { symbol: "BOSCHLTD", name: "Bosch", exchange: "NSE" },
  { symbol: "BEL", name: "Bharat Electronics", exchange: "NSE" },
  { symbol: "HAL", name: "Hindustan Aeronautics", exchange: "NSE" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", exchange: "NSE" },
  { symbol: "SAIL", name: "Steel Authority of India", exchange: "NSE" },
  { symbol: "NMDC", name: "NMDC", exchange: "NSE" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", exchange: "NSE" },
  { symbol: "PNB", name: "Punjab National Bank", exchange: "NSE" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", exchange: "NSE" },
  { symbol: "CANBK", name: "Canara Bank", exchange: "NSE" },
  { symbol: "UNIONBANK", name: "Union Bank of India", exchange: "NSE" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", exchange: "NSE" },
  { symbol: "FEDERALBNK", name: "Federal Bank", exchange: "NSE" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", exchange: "NSE" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", exchange: "NSE" },
  { symbol: "INDHOTEL", name: "Indian Hotels Company", exchange: "NSE" },
  { symbol: "TRENT", name: "Trent", exchange: "NSE" },
  { symbol: "DMART", name: "Avenue Supermarts", exchange: "NSE" },
  { symbol: "ZOMATO", name: "Zomato", exchange: "NSE" },
  { symbol: "ETERNAL", name: "Eternal", exchange: "NSE" },
  { symbol: "PAYTM", name: "One97 Communications (Paytm)", exchange: "NSE" },
  { symbol: "NYKAA", name: "FSN E-Commerce (Nykaa)", exchange: "NSE" },
  { symbol: "POLICYBZR", name: "PB Fintech (Policybazaar)", exchange: "NSE" },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism", exchange: "NSE" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation", exchange: "NSE" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", exchange: "NSE" },
  { symbol: "PFC", name: "Power Finance Corporation", exchange: "NSE" },
  { symbol: "RECLTD", name: "REC", exchange: "NSE" },
  { symbol: "LICI", name: "Life Insurance Corporation of India", exchange: "NSE" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", exchange: "NSE" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", exchange: "NSE" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management", exchange: "NSE" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance", exchange: "NSE" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", exchange: "NSE" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings & Investment", exchange: "NSE" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", exchange: "NSE" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance", exchange: "NSE" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", exchange: "NSE" },
  { symbol: "LTIM", name: "LTIMindtree", exchange: "NSE" },
  { symbol: "LTTS", name: "L&T Technology Services", exchange: "NSE" },
  { symbol: "PERSISTENT", name: "Persistent Systems", exchange: "NSE" },
  { symbol: "COFORGE", name: "Coforge", exchange: "NSE" },
  { symbol: "MPHASIS", name: "Mphasis", exchange: "NSE" },
  { symbol: "OFSS", name: "Oracle Financial Services Software", exchange: "NSE" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", exchange: "NSE" },
  { symbol: "TATAPOWER", name: "Tata Power Company", exchange: "NSE" },
  { symbol: "TORNTPOWER", name: "Torrent Power", exchange: "NSE" },
  { symbol: "JSWENERGY", name: "JSW Energy", exchange: "NSE" },
  { symbol: "SHREECEM", name: "Shree Cement", exchange: "NSE" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat", exchange: "NSE" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements", exchange: "NSE" },
  { symbol: "PIIND", name: "PI Industries", exchange: "NSE" },
  { symbol: "UPL", name: "UPL", exchange: "NSE" },
  { symbol: "SRF", name: "SRF", exchange: "NSE" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", exchange: "NSE" },
  { symbol: "AARTIIND", name: "Aarti Industries", exchange: "NSE" },
  { symbol: "TATACHEM", name: "Tata Chemicals", exchange: "NSE" },
  { symbol: "LUPIN", name: "Lupin", exchange: "NSE" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", exchange: "NSE" },
  { symbol: "BIOCON", name: "Biocon", exchange: "NSE" },
  { symbol: "ALKEM", name: "Alkem Laboratories", exchange: "NSE" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", exchange: "NSE" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", exchange: "NSE" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", exchange: "NSE" },
  { symbol: "MANKIND", name: "Mankind Pharma", exchange: "NSE" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", exchange: "NSE" },
  { symbol: "FORTIS", name: "Fortis Healthcare", exchange: "NSE" },
  { symbol: "DIXON", name: "Dixon Technologies (India)", exchange: "NSE" },
  { symbol: "POLYCAB", name: "Polycab India", exchange: "NSE" },
  { symbol: "KEI", name: "KEI Industries", exchange: "NSE" },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions", exchange: "NSE" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital", exchange: "NSE" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail", exchange: "NSE" },
  { symbol: "PAGEIND", name: "Page Industries", exchange: "NSE" },
  { symbol: "BERGEPAINT", name: "Berger Paints India", exchange: "NSE" },
  { symbol: "VOLTAS", name: "Voltas", exchange: "NSE" },
  { symbol: "BLUESTARCO", name: "Blue Star", exchange: "NSE" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", exchange: "NSE" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company", exchange: "NSE" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International", exchange: "NSE" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", exchange: "NSE" },
  { symbol: "MRF", name: "MRF", exchange: "NSE" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", exchange: "NSE" },
  { symbol: "ESCORTS", name: "Escorts Kubota", exchange: "NSE" },
  { symbol: "TIINDIA", name: "Tube Investments of India", exchange: "NSE" },
  { symbol: "CUMMINSIND", name: "Cummins India", exchange: "NSE" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)", exchange: "NSE" },
  { symbol: "IDEA", name: "Vodafone Idea", exchange: "NSE" },
  { symbol: "YESBANK", name: "Yes Bank", exchange: "NSE" },
  { symbol: "INDUSTOWER", name: "Indus Towers", exchange: "NSE" },
  { symbol: "PETRONET", name: "Petronet LNG", exchange: "NSE" },
  { symbol: "OIL", name: "Oil India", exchange: "NSE" },
  { symbol: "MGL", name: "Mahanagar Gas", exchange: "NSE" },
  { symbol: "IGL", name: "Indraprastha Gas", exchange: "NSE" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas", exchange: "NSE" },
  { symbol: "NHPC", name: "NHPC", exchange: "NSE" },
  { symbol: "SJVN", name: "SJVN", exchange: "NSE" },
  { symbol: "CONCOR", name: "Container Corporation of India", exchange: "NSE" },
  { symbol: "BHARATFORG", name: "Bharat Forge", exchange: "NSE" },
  { symbol: "ABBOTINDIA", name: "Abbott India", exchange: "NSE" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks", exchange: "NSE" },
  { symbol: "NAUKRI", name: "Info Edge (India)", exchange: "NSE" },
  { symbol: "INDIANB", name: "Indian Bank", exchange: "NSE" },
  { symbol: "MFSL", name: "Max Financial Services", exchange: "NSE" },
  { symbol: "VBL", name: "Varun Beverages", exchange: "NSE" },
  { symbol: "UNITDSPR", name: "United Spirits", exchange: "NSE" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects", exchange: "NSE" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", exchange: "NSE" },
  { symbol: "GODREJPROP", name: "Godrej Properties", exchange: "NSE" },
  { symbol: "LODHA", name: "Macrotech Developers (Lodha)", exchange: "NSE" },
  { symbol: "PHOENIXLTD", name: "The Phoenix Mills", exchange: "NSE" },
  { symbol: "SUPREMEIND", name: "Supreme Industries", exchange: "NSE" },
  { symbol: "ASTRAL", name: "Astral", exchange: "NSE" },
  { symbol: "BSE", name: "BSE", exchange: "NSE" },
  { symbol: "CDSL", name: "Central Depository Services (India)", exchange: "NSE" },
  { symbol: "ANGELONE", name: "Angel One", exchange: "NSE" },
  { symbol: "KPITTECH", name: "KPIT Technologies", exchange: "NSE" },
  { symbol: "OLAELEC", name: "Ola Electric Mobility", exchange: "NSE" },
  { symbol: "ZYDUSWELL", name: "Zydus Wellness", exchange: "NSE" },
  { symbol: "PATANJALI", name: "Patanjali Foods", exchange: "NSE" },
  { symbol: "HINDZINC", name: "Hindustan Zinc", exchange: "NSE" },
  { symbol: "NATIONALUM", name: "National Aluminium Company", exchange: "NSE" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corporation", exchange: "NSE" },
  { symbol: "BDL", name: "Bharat Dynamics", exchange: "NSE" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", exchange: "NSE" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard", exchange: "NSE" },
  { symbol: "IREDA", name: "Indian Renewable Energy Development Agency", exchange: "NSE" },
  { symbol: "NBCC", name: "NBCC (India)", exchange: "NSE" },
  { symbol: "SUZLON", name: "Suzlon Energy", exchange: "NSE" },
  { symbol: "BHARTIHEXA", name: "Bharti Hexacom", exchange: "NSE" },
  { symbol: "JIOFIN", name: "Jio Financial Services", exchange: "NSE" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", exchange: "NSE" },
  { symbol: "PNBHOUSING", name: "PNB Housing Finance", exchange: "NSE" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", exchange: "NSE" },
  { symbol: "IIFL", name: "IIFL Finance", exchange: "NSE" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp", exchange: "NSE" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance", exchange: "NSE" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services", exchange: "NSE" },
  { symbol: "DELHIVERY", name: "Delhivery", exchange: "NSE" },
  { symbol: "GMRAIRPORT", name: "GMR Airports", exchange: "NSE" },
  { symbol: "IDBI", name: "IDBI Bank", exchange: "NSE" },
  { symbol: "UCOBANK", name: "UCO Bank", exchange: "NSE" },
  { symbol: "CENTRALBK", name: "Central Bank of India", exchange: "NSE" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", exchange: "NSE" },
  { symbol: "IOB", name: "Indian Overseas Bank", exchange: "NSE" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation", exchange: "NSE" },
  { symbol: "MRPL", name: "Mangalore Refinery & Petrochemicals", exchange: "NSE" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India", exchange: "NSE" },
  { symbol: "TITAGARH", name: "Titagarh Rail Systems", exchange: "NSE" },
  { symbol: "JBMA", name: "JBM Auto", exchange: "NSE" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings", exchange: "NSE" },
  { symbol: "UNOMINDA", name: "UNO Minda", exchange: "NSE" },
  { symbol: "EXIDEIND", name: "Exide Industries", exchange: "NSE" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility", exchange: "NSE" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", exchange: "NSE" },
  { symbol: "GLAND", name: "Gland Pharma", exchange: "NSE" },
  { symbol: "IPCALAB", name: "Ipca Laboratories", exchange: "NSE" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma", exchange: "NSE" },
  { symbol: "SYNGENE", name: "Syngene International", exchange: "NSE" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", exchange: "NSE" },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs", exchange: "NSE" },
  { symbol: "KFINTECH", name: "KFin Technologies", exchange: "NSE" },
  { symbol: "CAMS", name: "Computer Age Management Services", exchange: "NSE" },
  { symbol: "MCX", name: "Multi Commodity Exchange of India", exchange: "NSE" },
  { symbol: "IEX", name: "Indian Energy Exchange", exchange: "NSE" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers & Petrochemicals", exchange: "NSE" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers & Chemicals", exchange: "NSE" },
  { symbol: "COROMANDEL", name: "Coromandel International", exchange: "NSE" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", exchange: "NSE" },
  { symbol: "FACT", name: "Fertilizers & Chemicals Travancore", exchange: "NSE" },
  { symbol: "BSOFT", name: "Birlasoft", exchange: "NSE" },
  { symbol: "CYIENT", name: "Cyient", exchange: "NSE" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies", exchange: "NSE" },
  { symbol: "TATATECH", name: "Tata Technologies", exchange: "NSE" },
  { symbol: "HONAUT", name: "Honeywell Automation India", exchange: "NSE" },
  { symbol: "THERMAX", name: "Thermax", exchange: "NSE" },
  { symbol: "AIAENG", name: "AIA Engineering", exchange: "NSE" },
  { symbol: "KAYNES", name: "Kaynes Technology India", exchange: "NSE" },
  { symbol: "SYRMA", name: "Syrma SGS Technology", exchange: "NSE" },
  { symbol: "AMBER", name: "Amber Enterprises India", exchange: "NSE" },
  { symbol: "PGEL", name: "PG Electroplast", exchange: "NSE" },
  { symbol: "WAAREEENER", name: "Waaree Energies", exchange: "NSE" },
  { symbol: "PREMIERENE", name: "Premier Energies", exchange: "NSE" },
  { symbol: "INOXWIND", name: "Inox Wind", exchange: "NSE" },
  { symbol: "CESC", name: "CESC", exchange: "NSE" },
  { symbol: "NLCINDIA", name: "NLC India", exchange: "NSE" },
  { symbol: "RPOWER", name: "Reliance Power", exchange: "NSE" },
  { symbol: "JPPOWER", name: "Jaiprakash Power Ventures", exchange: "NSE" },
  { symbol: "TATACOMM", name: "Tata Communications", exchange: "NSE" },
  { symbol: "HFCL", name: "HFCL", exchange: "NSE" },
  { symbol: "ROUTE", name: "Route Mobile", exchange: "NSE" },
  { symbol: "TANLA", name: "Tanla Platforms", exchange: "NSE" },
  { symbol: "RBLBANK", name: "RBL Bank", exchange: "NSE" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", exchange: "NSE" },
  { symbol: "CUB", name: "City Union Bank", exchange: "NSE" },
  { symbol: "J&KBANK", name: "Jammu & Kashmir Bank", exchange: "NSE" },
  { symbol: "SOUTHBANK", name: "South Indian Bank", exchange: "NSE" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", exchange: "NSE" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", exchange: "NSE" },
  { symbol: "GICRE", name: "General Insurance Corporation of India", exchange: "NSE" },
  { symbol: "NIACL", name: "The New India Assurance Company", exchange: "NSE" },
  { symbol: "STARHEALTH", name: "Star Health & Allied Insurance", exchange: "NSE" },
  { symbol: "MEDANTA", name: "Global Health (Medanta)", exchange: "NSE" },
  { symbol: "NH", name: "Narayana Hrudayalaya", exchange: "NSE" },
  { symbol: "KIMS", name: "Krishna Institute of Medical Sciences", exchange: "NSE" },
  { symbol: "RAINBOW", name: "Rainbow Children's Medicare", exchange: "NSE" },
  { symbol: "DEVYANI", name: "Devyani International", exchange: "NSE" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India", exchange: "NSE" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld", exchange: "NSE" },
  { symbol: "VARROC", name: "Varroc Engineering", exchange: "NSE" },
  { symbol: "ENDURANCE", name: "Endurance Technologies", exchange: "NSE" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India", exchange: "NSE" },
  { symbol: "TIMKEN", name: "Timken India", exchange: "NSE" },
  { symbol: "SKFINDIA", name: "SKF India", exchange: "NSE" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal", exchange: "NSE" },
  { symbol: "GRINDWELL", name: "Grindwell Norton", exchange: "NSE" },
  { symbol: "FINPIPE", name: "Finolex Industries", exchange: "NSE" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", exchange: "NSE" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes", exchange: "NSE" },
  { symbol: "WELCORP", name: "Welspun Corp", exchange: "NSE" },
  { symbol: "JINDALSAW", name: "Jindal Saw", exchange: "NSE" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints", exchange: "NSE" },
  { symbol: "AKZOINDIA", name: "Akzo Nobel India", exchange: "NSE" },
  { symbol: "INDIGOPNTS", name: "Indigo Paints", exchange: "NSE" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals", exchange: "NSE" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India", exchange: "NSE" },
  { symbol: "VGUARD", name: "V-Guard Industries", exchange: "NSE" },
  { symbol: "BAJAJELEC", name: "Bajaj Electricals", exchange: "NSE" },
  { symbol: "RAYMOND", name: "Raymond", exchange: "NSE" },
  { symbol: "ARVIND", name: "Arvind", exchange: "NSE" },
  { symbol: "TRIDENT", name: "Trident", exchange: "NSE" },
  { symbol: "WELSPUNLIV", name: "Welspun Living", exchange: "NSE" },
  { symbol: "KPRMILL", name: "K.P.R. Mill", exchange: "NSE" },
  { symbol: "VTL", name: "Vardhman Textiles", exchange: "NSE" },
  { symbol: "CEATLTD", name: "CEAT", exchange: "NSE" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries", exchange: "NSE" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services", exchange: "NSE" },
  { symbol: "360ONE", name: "360 ONE WAM", exchange: "NSE" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management", exchange: "NSE" },
  { symbol: "ANANDRATHI", name: "Anand Rathi Wealth", exchange: "NSE" },
  { symbol: "PPLPHARMA", name: "Piramal Pharma", exchange: "NSE" },
  { symbol: "PEL", name: "Piramal Enterprises", exchange: "NSE" },
  { symbol: "GODREJIND", name: "Godrej Industries", exchange: "NSE" },
  { symbol: "SOBHA", name: "Sobha", exchange: "NSE" },
  { symbol: "BRIGADE", name: "Brigade Enterprises", exchange: "NSE" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers", exchange: "NSE" },
];

/**
 * Full master, indices first then equities, de-duplicated by symbol (the first
 * occurrence wins so indices keep priority over any same-named equity).
 */
export const SYMBOL_MASTER: readonly SymbolInfo[] = (() => {
  const seen = new Set<string>();
  const list: SymbolInfo[] = [];
  for (const info of [...INDICES, ...STOCKS]) {
    if (seen.has(info.symbol)) continue;
    seen.add(info.symbol);
    list.push(info);
  }
  return list;
})();

/** All known symbols, indices first. De-duplicated (kept for back-compat). */
export const COMMON_SYMBOLS: readonly string[] = SYMBOL_MASTER.map((s) => s.symbol);

/** Fast symbol -> info map for O(1) lookups. */
const SYMBOL_MAP = new Map<string, SymbolInfo>(SYMBOL_MASTER.map((s) => [s.symbol, s]));

/**
 * Normalize a raw cashtag / ticker into the canonical uppercase symbol token.
 * Trims, strips a leading `$`, and uppercases. Returns "" for empty input.
 */
export function normalizeSymbol(raw: string): string {
  return raw.trim().replace(/^\$+/, "").toUpperCase();
}

/** True when the (normalized) symbol is in the curated master. */
export function isKnownSymbol(symbol: string): boolean {
  return SYMBOL_MAP.has(normalizeSymbol(symbol));
}

/** Looks up the master record for a symbol (case-insensitive), or null. */
export function lookupSymbol(symbol: string): SymbolInfo | null {
  return SYMBOL_MAP.get(normalizeSymbol(symbol)) ?? null;
}
